package com.akocis.babysleeptracker.ui.screen

import android.app.Activity
import android.content.Intent
import android.graphics.Bitmap
import android.graphics.BitmapFactory
import android.net.Uri
import android.view.WindowManager
import androidx.activity.compose.rememberLauncherForActivityResult
import androidx.activity.result.contract.ActivityResultContracts
import androidx.compose.animation.AnimatedContent
import androidx.compose.animation.fadeIn
import androidx.compose.animation.fadeOut
import androidx.compose.animation.slideInHorizontally
import androidx.compose.animation.slideOutHorizontally
import androidx.compose.animation.togetherWith
import androidx.compose.foundation.Image
import androidx.compose.foundation.background
import androidx.compose.foundation.gestures.detectTapGestures
import androidx.compose.foundation.layout.Arrangement
import androidx.compose.foundation.layout.Box
import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.ExperimentalLayoutApi
import androidx.compose.foundation.layout.FlowRow
import androidx.compose.foundation.layout.Row
import androidx.compose.foundation.layout.Spacer
import androidx.compose.foundation.layout.fillMaxSize
import androidx.compose.foundation.layout.fillMaxWidth
import androidx.compose.foundation.layout.height
import androidx.compose.foundation.layout.padding
import androidx.compose.foundation.rememberScrollState
import androidx.compose.foundation.verticalScroll
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.automirrored.filled.ArrowBack
import androidx.compose.material.icons.filled.Folder
import androidx.compose.material.icons.filled.PlayArrow
import androidx.compose.material3.Card
import androidx.compose.material3.CardDefaults
import androidx.compose.material3.ExperimentalMaterial3Api
import androidx.compose.material3.FilterChip
import androidx.compose.material3.Icon
import androidx.compose.material3.IconButton
import androidx.compose.material3.MaterialTheme
import androidx.compose.material3.OutlinedButton
import androidx.compose.material3.Scaffold
import androidx.compose.material3.SegmentedButton
import androidx.compose.material3.SegmentedButtonDefaults
import androidx.compose.material3.SingleChoiceSegmentedButtonRow
import androidx.compose.material3.Slider
import androidx.compose.material3.Switch
import androidx.compose.material3.Text
import androidx.compose.material3.TopAppBar
import androidx.compose.material3.TopAppBarDefaults
import androidx.compose.runtime.Composable
import androidx.compose.runtime.DisposableEffect
import androidx.compose.runtime.LaunchedEffect
import androidx.compose.runtime.getValue
import androidx.compose.runtime.mutableIntStateOf
import androidx.compose.runtime.mutableStateOf
import androidx.compose.runtime.remember
import androidx.compose.runtime.setValue
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.asImageBitmap
import androidx.compose.ui.input.pointer.pointerInput
import androidx.compose.ui.layout.ContentScale
import androidx.compose.ui.layout.onSizeChanged
import androidx.compose.ui.platform.LocalContext
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.unit.dp
import androidx.documentfile.provider.DocumentFile
import com.akocis.babysleeptracker.model.HighContrastEntry
import com.akocis.babysleeptracker.repository.EntryParser
import com.akocis.babysleeptracker.repository.FileRepository
import com.akocis.babysleeptracker.repository.PreferencesRepository
import com.akocis.babysleeptracker.repository.SyncHelper
import com.akocis.babysleeptracker.ui.component.ColorScheme
import com.akocis.babysleeptracker.ui.component.HighContrastImageGenerator
import com.akocis.babysleeptracker.ui.component.PatternType
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.Job
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import java.time.LocalDate
import java.time.LocalTime

enum class TransitionType(val label: String) {
    NONE("None"),
    FADE("Fade"),
    SLIDE("Slide");
}

@OptIn(ExperimentalMaterial3Api::class, ExperimentalLayoutApi::class)
@Composable
fun HighContrastScreen(
    prefsRepository: PreferencesRepository,
    fileRepository: FileRepository,
    onBack: () -> Unit
) {
    val context = LocalContext.current

    var useGenerated by remember { mutableStateOf(prefsRepository.hcUseGenerated) }
    var slideshow by remember { mutableStateOf(prefsRepository.hcSlideshow) }
    var slideshowDelay by remember { mutableStateOf(prefsRepository.hcSlideshowDelay) }
    var transition by remember { mutableStateOf(TransitionType.entries.find { it.name == prefsRepository.hcTransition } ?: TransitionType.FADE) }
    var keepScreenOn by remember { mutableStateOf(prefsRepository.hcKeepScreenOn) }
    var folderUri by remember { mutableStateOf(prefsRepository.hcFolderUri?.let { Uri.parse(it) }) }
    var enabledPatterns by remember {
        mutableStateOf(
            prefsRepository.hcEnabledPatterns.let { saved ->
                if (saved.isBlank()) PatternType.entries.toSet()
                else saved.split(",").mapNotNull { name -> PatternType.entries.find { it.name == name } }.toSet()
            }
        )
    }
    var enabledColors by remember {
        mutableStateOf(
            prefsRepository.hcEnabledColors.let { saved ->
                if (saved.isBlank()) setOf(ColorScheme.BLACK_WHITE, ColorScheme.WHITE_BLACK, ColorScheme.RED_WHITE)
                else saved.split(",").mapNotNull { name -> ColorScheme.entries.find { it.name == name } }.toSet()
            }
        )
    }

    var showViewer by remember { mutableStateOf(false) }

    val folderPickerLauncher = rememberLauncherForActivityResult(
        ActivityResultContracts.StartActivityForResult()
    ) { result ->
        if (result.resultCode == Activity.RESULT_OK) {
            result.data?.data?.let { uri ->
                context.contentResolver.takePersistableUriPermission(
                    uri,
                    Intent.FLAG_GRANT_READ_URI_PERMISSION
                )
                folderUri = uri
                prefsRepository.hcFolderUri = uri.toString()
            }
        }
    }

    fun savePrefs() {
        prefsRepository.hcUseGenerated = useGenerated
        prefsRepository.hcSlideshow = slideshow
        prefsRepository.hcSlideshowDelay = slideshowDelay
        prefsRepository.hcTransition = transition.name
        prefsRepository.hcKeepScreenOn = keepScreenOn
        prefsRepository.hcEnabledPatterns = enabledPatterns.joinToString(",") { it.name }
        prefsRepository.hcEnabledColors = enabledColors.joinToString(",") { it.name }
    }

    if (showViewer) {
        HighContrastViewer(
            prefsRepository = prefsRepository,
            fileRepository = fileRepository,
            useGenerated = useGenerated,
            slideshow = slideshow,
            slideshowDelay = slideshowDelay,
            transition = transition,
            keepScreenOn = keepScreenOn,
            enabledPatterns = enabledPatterns,
            enabledColors = enabledColors,
            folderUri = folderUri,
            onExit = { showViewer = false }
        )
        return
    }

    Scaffold(
        topBar = {
            TopAppBar(
                title = { Text("High Contrast Images") },
                colors = TopAppBarDefaults.topAppBarColors(
                    containerColor = MaterialTheme.colorScheme.primary,
                    titleContentColor = MaterialTheme.colorScheme.onPrimary
                ),
                navigationIcon = {
                    IconButton(onClick = onBack) {
                        Icon(
                            Icons.AutoMirrored.Filled.ArrowBack, "Back",
                            tint = MaterialTheme.colorScheme.onPrimary
                        )
                    }
                }
            )
        }
    ) { padding ->
        Column(
            modifier = Modifier
                .fillMaxSize()
                .padding(padding)
                .verticalScroll(rememberScrollState())
                .padding(16.dp)
        ) {
            // Source selector
            Card(
                modifier = Modifier.fillMaxWidth(),
                colors = CardDefaults.cardColors(containerColor = MaterialTheme.colorScheme.surface)
            ) {
                Column(modifier = Modifier.padding(16.dp)) {
                    Text("Image Source", style = MaterialTheme.typography.titleMedium, fontWeight = FontWeight.Bold)
                    Spacer(modifier = Modifier.height(8.dp))
                    SingleChoiceSegmentedButtonRow(modifier = Modifier.fillMaxWidth()) {
                        val options = listOf(true to "Generated", false to "Folder")
                        options.forEachIndexed { index, (gen, label) ->
                            SegmentedButton(
                                selected = useGenerated == gen,
                                onClick = {
                                    useGenerated = gen
                                    savePrefs()
                                },
                                shape = SegmentedButtonDefaults.itemShape(index = index, count = options.size)
                            ) { Text(label) }
                        }
                    }

                    if (!useGenerated) {
                        Spacer(modifier = Modifier.height(8.dp))
                        OutlinedButton(
                            onClick = {
                                val intent = Intent(Intent.ACTION_OPEN_DOCUMENT_TREE)
                                folderPickerLauncher.launch(intent)
                            },
                            modifier = Modifier.fillMaxWidth()
                        ) {
                            Icon(Icons.Default.Folder, null, modifier = Modifier.padding(end = 8.dp))
                            Text(
                                if (folderUri != null) {
                                    val doc = DocumentFile.fromTreeUri(context, folderUri!!)
                                    doc?.name ?: "Selected folder"
                                } else "Choose Image Folder"
                            )
                        }
                    }
                }
            }

            // Generated image settings
            if (useGenerated) {
                Spacer(modifier = Modifier.height(12.dp))
                Card(
                    modifier = Modifier.fillMaxWidth(),
                    colors = CardDefaults.cardColors(containerColor = MaterialTheme.colorScheme.surface)
                ) {
                    Column(modifier = Modifier.padding(16.dp)) {
                        Text("Patterns", style = MaterialTheme.typography.titleMedium, fontWeight = FontWeight.Bold)
                        Spacer(modifier = Modifier.height(8.dp))
                        FlowRow(
                            horizontalArrangement = Arrangement.spacedBy(6.dp),
                            verticalArrangement = Arrangement.spacedBy(0.dp)
                        ) {
                            PatternType.entries.forEach { pt ->
                                FilterChip(
                                    selected = pt in enabledPatterns,
                                    onClick = {
                                        enabledPatterns = if (pt in enabledPatterns && enabledPatterns.size > 1)
                                            enabledPatterns - pt else enabledPatterns + pt
                                        savePrefs()
                                    },
                                    label = { Text(pt.label) }
                                )
                            }
                        }

                        Spacer(modifier = Modifier.height(12.dp))
                        Text("Colors", style = MaterialTheme.typography.titleMedium, fontWeight = FontWeight.Bold)
                        Spacer(modifier = Modifier.height(8.dp))
                        FlowRow(
                            horizontalArrangement = Arrangement.spacedBy(6.dp),
                            verticalArrangement = Arrangement.spacedBy(0.dp)
                        ) {
                            ColorScheme.entries.forEach { cs ->
                                FilterChip(
                                    selected = cs in enabledColors,
                                    onClick = {
                                        enabledColors = if (cs in enabledColors && enabledColors.size > 1)
                                            enabledColors - cs else enabledColors + cs
                                        savePrefs()
                                    },
                                    label = { Text(cs.label) }
                                )
                            }
                        }
                    }
                }
            }

            Spacer(modifier = Modifier.height(12.dp))

            // Slideshow settings
            Card(
                modifier = Modifier.fillMaxWidth(),
                colors = CardDefaults.cardColors(containerColor = MaterialTheme.colorScheme.surface)
            ) {
                Column(modifier = Modifier.padding(16.dp)) {
                    Text("Slideshow", style = MaterialTheme.typography.titleMedium, fontWeight = FontWeight.Bold)
                    Spacer(modifier = Modifier.height(8.dp))
                    Row(
                        modifier = Modifier.fillMaxWidth(),
                        horizontalArrangement = Arrangement.SpaceBetween,
                        verticalAlignment = Alignment.CenterVertically
                    ) {
                        Text("Auto-advance")
                        Switch(
                            checked = slideshow,
                            onCheckedChange = {
                                slideshow = it
                                savePrefs()
                            }
                        )
                    }
                    if (slideshow) {
                        Spacer(modifier = Modifier.height(4.dp))
                        Text("Delay: ${slideshowDelay}s")
                        Slider(
                            value = slideshowDelay.toFloat(),
                            onValueChange = {
                                slideshowDelay = it.toInt()
                                savePrefs()
                            },
                            valueRange = 2f..60f,
                            steps = 28
                        )
                    }
                    Spacer(modifier = Modifier.height(4.dp))
                    Text("Transition", style = MaterialTheme.typography.bodyMedium)
                    Spacer(modifier = Modifier.height(4.dp))
                    SingleChoiceSegmentedButtonRow(modifier = Modifier.fillMaxWidth()) {
                        TransitionType.entries.forEachIndexed { index, tt ->
                            SegmentedButton(
                                selected = transition == tt,
                                onClick = {
                                    transition = tt
                                    savePrefs()
                                },
                                shape = SegmentedButtonDefaults.itemShape(index = index, count = TransitionType.entries.size)
                            ) { Text(tt.label) }
                        }
                    }
                }
            }

            Spacer(modifier = Modifier.height(12.dp))

            // Display settings
            Card(
                modifier = Modifier.fillMaxWidth(),
                colors = CardDefaults.cardColors(containerColor = MaterialTheme.colorScheme.surface)
            ) {
                Column(modifier = Modifier.padding(16.dp)) {
                    Text("Display", style = MaterialTheme.typography.titleMedium, fontWeight = FontWeight.Bold)
                    Spacer(modifier = Modifier.height(8.dp))
                    Row(
                        modifier = Modifier.fillMaxWidth(),
                        horizontalArrangement = Arrangement.SpaceBetween,
                        verticalAlignment = Alignment.CenterVertically
                    ) {
                        Text("Keep screen on")
                        Switch(
                            checked = keepScreenOn,
                            onCheckedChange = {
                                keepScreenOn = it
                                savePrefs()
                            }
                        )
                    }
                }
            }

            Spacer(modifier = Modifier.height(24.dp))

            // Start button
            OutlinedButton(
                onClick = {
                    savePrefs()
                    showViewer = true
                },
                modifier = Modifier
                    .fillMaxWidth()
                    .height(64.dp),
                enabled = useGenerated || folderUri != null
            ) {
                Icon(Icons.Default.PlayArrow, null, modifier = Modifier.padding(end = 8.dp))
                Text("Start Slideshow", style = MaterialTheme.typography.titleMedium)
            }

            Spacer(modifier = Modifier.height(16.dp))
            Text(
                "Tap to change image. Double-tap to exit.",
                style = MaterialTheme.typography.bodySmall,
                color = MaterialTheme.colorScheme.onSurface.copy(alpha = 0.5f),
                modifier = Modifier.fillMaxWidth()
            )
            Spacer(modifier = Modifier.height(16.dp))
        }
    }
}

@Composable
private fun HighContrastViewer(
    prefsRepository: PreferencesRepository,
    fileRepository: FileRepository,
    useGenerated: Boolean,
    slideshow: Boolean,
    slideshowDelay: Int,
    transition: TransitionType,
    keepScreenOn: Boolean,
    enabledPatterns: Set<PatternType>,
    enabledColors: Set<ColorScheme>,
    folderUri: Uri?,
    onExit: () -> Unit
) {
    val context = LocalContext.current

    // Build color abbreviation string
    val colorsAbbrev = remember(enabledColors) {
        enabledColors.joinToString(",") { cs ->
            cs.name.split("_").joinToString("") { it.first().toString() }
        }
    }

    // Log HC entry: append ongoing on start, update to completed on exit
    val startDate = remember { LocalDate.now() }
    val startTime = remember { LocalTime.now().withSecond(0).withNano(0) }
    val entryId = remember { EntryParser.generateId() }
    DisposableEffect(Unit) {
        val uri = prefsRepository.fileUri
        var appendJob: Job? = null
        if (uri != null) {
            val entry = HighContrastEntry(startDate, startTime, null, colorsAbbrev, entryId)
            appendJob = CoroutineScope(Dispatchers.IO).launch {
                try {
                    fileRepository.appendHighContrastEntry(uri, entry)
                    SyncHelper.notifyDataChanged()
                } catch (_: Exception) {}
            }
        }
        onDispose {
            if (uri != null) {
                CoroutineScope(Dispatchers.IO).launch {
                    try {
                        appendJob?.join()
                        val endTime = LocalTime.now().withSecond(0).withNano(0)
                        val completed = HighContrastEntry(startDate, startTime, endTime, colorsAbbrev)
                        val completedLine = EntryParser.formatHighContrastEntry(completed)
                        fileRepository.replaceById(uri, entryId, completedLine)
                        SyncHelper.notifyDataChanged()
                    } catch (_: Exception) {}
                }
            }
        }
    }

    // Keep screen on
    val activity = context as? Activity
    DisposableEffect(keepScreenOn) {
        if (keepScreenOn) {
            activity?.window?.addFlags(WindowManager.LayoutParams.FLAG_KEEP_SCREEN_ON)
        }
        onDispose {
            activity?.window?.clearFlags(WindowManager.LayoutParams.FLAG_KEEP_SCREEN_ON)
        }
    }

    // Load folder images list
    val folderImages = remember(folderUri, useGenerated) {
        if (useGenerated || folderUri == null) emptyList()
        else {
            val dir = DocumentFile.fromTreeUri(context, folderUri)
            dir?.listFiles()
                ?.filter { it.isFile && it.type?.startsWith("image/") == true }
                ?.mapNotNull { it.uri }
                ?: emptyList()
        }
    }

    var imageIndex by remember { mutableIntStateOf(0) }
    var seed by remember { mutableStateOf(System.currentTimeMillis()) }
    var viewerWidth by remember { mutableIntStateOf(1080) }
    var viewerHeight by remember { mutableIntStateOf(1920) }

    val currentBitmap = remember(seed, imageIndex, viewerWidth, viewerHeight) {
        if (useGenerated) {
            if (viewerWidth > 0 && viewerHeight > 0) {
                HighContrastImageGenerator.generateRandom(
                    viewerWidth, viewerHeight, enabledPatterns, enabledColors, seed
                )
            } else null
        } else {
            if (folderImages.isNotEmpty()) {
                val idx = imageIndex % folderImages.size
                try {
                    context.contentResolver.openInputStream(folderImages[idx])?.use { stream ->
                        BitmapFactory.decodeStream(stream)
                    }
                } catch (_: Exception) { null }
            } else null
        }
    }

    fun nextImage() {
        if (useGenerated) {
            seed = System.currentTimeMillis()
        } else {
            if (folderImages.isNotEmpty()) {
                imageIndex = (imageIndex + 1) % folderImages.size
            }
        }
    }

    // Auto-advance
    LaunchedEffect(slideshow, slideshowDelay, seed, imageIndex) {
        if (slideshow) {
            delay(slideshowDelay * 1000L)
            nextImage()
        }
    }

    val animContent: @Composable (Bitmap?) -> Unit = { bitmap ->
        if (bitmap != null) {
            Image(
                bitmap = bitmap.asImageBitmap(),
                contentDescription = "High contrast image",
                contentScale = ContentScale.Fit,
                modifier = Modifier.fillMaxSize()
            )
        }
    }

    Box(
        modifier = Modifier
            .fillMaxSize()
            .background(Color.Black)
            .onSizeChanged { size ->
                viewerWidth = size.width.coerceAtLeast(1)
                viewerHeight = size.height.coerceAtLeast(1)
            }
            .pointerInput(Unit) {
                detectTapGestures(
                    onTap = { nextImage() },
                    onDoubleTap = { onExit() }
                )
            },
        contentAlignment = Alignment.Center
    ) {
        when (transition) {
            TransitionType.NONE -> {
                animContent(currentBitmap)
            }
            TransitionType.FADE -> {
                val key = if (useGenerated) seed else imageIndex
                AnimatedContent(
                    targetState = key,
                    transitionSpec = { fadeIn() togetherWith fadeOut() },
                    label = "fade"
                ) { _ ->
                    animContent(currentBitmap)
                }
            }
            TransitionType.SLIDE -> {
                val key = if (useGenerated) seed else imageIndex
                AnimatedContent(
                    targetState = key,
                    transitionSpec = {
                        slideInHorizontally { it } togetherWith slideOutHorizontally { -it }
                    },
                    label = "slide"
                ) { _ ->
                    animContent(currentBitmap)
                }
            }
        }
    }
}
